name: Manual test
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+
  workflow_dispatch:

env:
  FOO: bar

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Say hi
        run: |
          echo "Hello world"
      - name: Export envvars
        run: |
          echo "TRIGGER=triggered" >> $GITHUB_ENV
      - name: Echo the event
        env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
      - name: Echo the event_name
        run: |
          echo "event name is:" ${{ github.event_name }}
      - name: Echo envvars
        run: |
          echo "FOO=$FOO && TRIGGER=$TRIGGER"
